/**
 * Swagger / API examples aligned with prisma/seed.ts (typical insert order).
 */
export const SEED = {
  admin: {
    id: '1',
    full_name: 'System Admin',
    email: 'admin@technoamar.ps',
    password: 'Admin@1234',
    employee_id: 'EMP-ADMIN-001',
    phone: '+970599000001',
    city: 'GAZA',
    role: 'ADMIN',
  },
  citizen: {
    id: '2',
    full_name: 'Ahmed Al-Citizen',
    email: 'citizen@technoamar.ps',
    password: 'Citizen@1234',
    national_id: '123456789',
    phone: '+970599000002',
    city: 'KHAN',
    role: 'CITIZEN',
  },
  employee: {
    id: '3',
    full_name: 'Sara Al-Employee',
    email: 'employee@technoamar.ps',
    password: 'Employee@1234',
    employee_id: 'EMP-001',
    phone: '+970599000003',
    city: 'MIDDLE',
    role: 'EMPLOYEE',
  },
  manager: {
    id: '4',
    full_name: 'Omar Al-Manager',
    email: 'manager@technoamar.ps',
    password: 'Manager@1234',
    employee_id: 'EMP-MGR-001',
    phone: '+970599000004',
    city: 'NORTH',
    role: 'DEPARTMENT_MANAGER',
  },
  pendingCitizen: {
    id: '5',
    full_name: 'Fatima Pending',
    email: 'pending@technoamar.ps',
    password: 'Pending@1234',
    national_id: '987654321',
    phone: '+970599000005',
    city: 'RAFAH',
    role: 'CITIZEN',
  },
  department: {
    municipalServices: { id: '1', name: 'Municipal Services' },
    publicWorks: { id: '2', name: 'Public Works' },
    urbanPlanning: { id: '3', name: 'Urban Planning' },
  },
  section: {
    permitsDesk: { id: '1', name: 'Permits Desk' },
    licensingOffice: { id: '2', name: 'Licensing Office' },
    roadMaintenance: { id: '3', name: 'Road Maintenance' },
    zoningBoard: { id: '5', name: 'Zoning Board' },
  },
  service: {
    buildingPermit: { id: '1', name: 'Building Permit' },
    tradeLicense: { id: '2', name: 'Trade License' },
    zoningCertificate: { id: '3', name: 'Zoning Certificate' },
    roadRepairRequest: { id: '4', name: 'Road Repair Request' },
  },
} as const;
